/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dmrr.asistenciasx;

import au.com.bytecode.opencsv.CSVReader;
import au.com.bytecode.opencsv.CSVWriter;
import static com.dmrr.asistenciasx.SIIAUConnector.getFecha;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang.ArrayUtils;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.codehaus.plexus.util.FileUtils;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author diegomichel
 */
public class ReporteDeHorarios extends javax.swing.JFrame {

    String sessionId;
    String sessionId2;

    Map<String, String> carreras;
    Map<String, String> diasDeLaSemana;

    /**
     * Creates new form ReporteDeHorarios
     */
    public ReporteDeHorarios() {
        diasDeLaSemana = new HashMap<>();
        carreras = new HashMap<>();
        diasDeLaSemana.put("lup", "M");
        diasDeLaSemana.put("map", "T");
        diasDeLaSemana.put("mip", "W");
        diasDeLaSemana.put("jup", "R");
        diasDeLaSemana.put("vip", "F");
        diasDeLaSemana.put("sap", "S");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldNIP = new javax.swing.JPasswordField();
        jButtonLoginSIIAU = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Acceso a SIIAU"));

        jLabel1.setText("Codigo");

        jTextFieldCodigo.setText("2225255");

        jLabel2.setText("NIP");

        jPasswordFieldNIP.setText("5255");

        jButtonLoginSIIAU.setText("Conectar");
        jButtonLoginSIIAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginSIIAUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldNIP))
                .addGap(13, 13, 13))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLoginSIIAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLoginSIIAU)
                .addContainerGap())
        );

        jButton1.setText("Horarios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginSIIAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginSIIAUActionPerformed
        try {
            if (jButtonLoginSIIAU.getText().equals("Desconectar")) {
                jButtonLoginSIIAU.setText("Conectar");
                jPanel3.setEnabled(true);
                jTextFieldCodigo.setEnabled(true);
                jPasswordFieldNIP.setEnabled(true);
                jLabel1.setEnabled(true);
                jLabel2.setEnabled(true);
                sessionId = "";
                sessionId2 = "";
                return;
            }

            org.jsoup.Connection.Response respuesta = Jsoup.connect("http://siiauescolar.siiau.udg.mx/wus/gupprincipal.valida_inicio")
                    .data("p_codigo_c", jTextFieldCodigo.getText(), "p_clave_c", jPasswordFieldNIP.getText())
                    .method(org.jsoup.Connection.Method.POST)
                    .timeout(0)
                    .execute();

            Document login = respuesta.parse();
            sessionId = respuesta.cookie(getFecha() + "SIIAUSESION");
            sessionId2 = respuesta.cookie(getFecha() + "SIIAUUDG");
            if (sessionId == null) {
                JOptionPane.showMessageDialog(rootPane, "Cheque que la fecha de su Sistema Operativo sea la correcta.");
                return;
            }
            if (login.toString().contains("no son validos")) {
                JOptionPane.showMessageDialog(rootPane, "Datos de acceso incorrecto.");
            } else {
                jPanel3.setEnabled(false);
                jTextFieldCodigo.setEnabled(false);
                jPasswordFieldNIP.setEnabled(false);
                jLabel1.setEnabled(false);
                jLabel2.setEnabled(false);
                jButtonLoginSIIAU.setText("Desconectar");

                Document formaDeConsultaAcademica = Jsoup.connect("http://siiauescolar.siiau.udg.mx/wse/sspsecc.lista_deptos?cup=J")
                        .userAgent("Mozilla")
                        .cookie(getFecha() + "SIIAUSESION", sessionId)
                        .cookie(getFecha() + "SIIAUUDG", sessionId2)
                        .timeout(0)
                        .post();
                

                Element firstTable = formaDeConsultaAcademica.select("body > table").first();
                Elements departamentosTRS = firstTable.select("tbody > tr");
                for (Element departamentoHR : departamentosTRS.subList(1, departamentosTRS.size())) {
                    //departamentos.put(departamentoHR.select("td:eq(1)").first().text(), departamentoHR.select("td:eq(0)").first().text());
                    //jComboBoxDepartamento.addItem(departamentoHR.select("td:eq(1)").first().text());
                }

                Document paginaDeCarreras = Jsoup.connect("http://siiauescolar.siiau.udg.mx/wse/sspsecc.lista_carreras?cup=J")
                        .userAgent("Mozilla")
                        .cookie(getFecha() + "SIIAUSESION", sessionId)
                        .cookie(getFecha() + "SIIAUUDG", sessionId2)
                        .timeout(0)
                        .post();
                Element tablaDeCarreras = paginaDeCarreras.select("body > table").first();
                Elements carrerasTR = tablaDeCarreras.select("tbody > tr");
                for (Element carreraHR : carrerasTR.subList(1, carrerasTR.size())) {
                    carreras.put(carreraHR.select("td:eq(0)").first().text(), carreraHR.select("td:eq(1)").first().text());
                    //System.out.println(carreraHR.select("td:eq(1)").first().text());
                    //System.out.println(carreraHR.select("td:eq(0)").first().text());
                }
                for (Map.Entry<String, String> entrySet : carreras.entrySet()) {
                    String key = entrySet.getKey();
                    String value = entrySet.getValue();
                    System.out.println(value+"-"+key);
                    
                }
                

            }
        } catch (IOException ex) {
            Logger.getLogger(SIIAUConnector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLoginSIIAUActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            File theDir = new File("reportesDeHorarios");
            theDir.mkdir();
            try {
                FileUtils.cleanDirectory(theDir);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, "Cierre los reportes abiertos primero.");
            }

            // TODO add your handling code here:
            /*
             ciclop:201510
             cup:J
             majrp:ADM
             majrdescp:LIC EN ADMINISTRACION
             deptop:4030
             lup:M
             map:T
             mip:W
             jup:R
             vip:F
             sap:S
             secp:A
             regp:T
             ordenp:0
             mostrarp:100
             tipop:D
             */
            for (Map.Entry<String, String> entrySet : carreras.entrySet()) {
                String carrera = entrySet.getKey();
                String carreraLargo = entrySet.getValue();
                //System.out.println(key + " - " + value);
                for (Map.Entry<String, String> entrySet2 : diasDeLaSemana.entrySet()) {
                    String key2 = entrySet2.getKey();
                    String value2 = entrySet2.getValue();
                    System.out.println(key2 + " - " + value2);

                    String dia = "";
                    if (key2.equals("lup")) {
                        dia = "Lunes";
                    }
                    if (key2.equals("map")) {
                        dia = "Martes";
                    }
                    if (key2.equals("mip")) {
                        dia = "Miércoles";
                    }
                    if (key2.equals("jup")) {
                        dia = "Jueves";
                    }
                    if (key2.equals("vip")) {
                        dia = "Viernes";
                    }
                    if (key2.equals("sap")) {
                        dia = "Sábado";
                    }

                    Document listaHorarios = Jsoup.connect("http://siiauescolar.siiau.udg.mx/wse/sspsecc.consulta_oferta")
                            .data("ciclop", "201510", "cup", "J", "deptop", "4030", "ordenp", "0", "mostrarp", "1000", "tipop", "D", "secp", "A", "regp", "T")
                            .data(key2, value2)
                            .data("majrp", carrera)
                            .data("majrdescp", carreraLargo)
                            .userAgent("Mozilla")
                            .cookie(getFecha() + "SIIAUSESION", sessionId)
                            .cookie(getFecha() + "SIIAUUDG", sessionId2)
                            .timeout(0)
                            .post();
                    System.out.println(key2+"-"+value2);

           // System.out.println(listaHorarios.text());
                    CSVReader reader = new CSVReader(new StringReader(listaHorarios.text()));

                    CSVWriter writer = new CSVWriter(new FileWriter("reportesDeHorarios\\"+carrera+"_"+carreraLargo+"_"+dia+".csv"), ',');
                    String[] title = null;
                    title = (String[]) ArrayUtils.add(title, carreraLargo+" - "+dia);
                    writer.writeNext(title);

                    // feed in your array (or convert your data to an array)
                    List<String[]> entries = reader.readAll();

                    for (String[] entry : entries) {

                        entry = (String[]) ArrayUtils.remove(entry, 1);
                        if(entry.length < 1) continue;
                        entry = (String[]) ArrayUtils.remove(entry, 1);
                        entry = (String[]) ArrayUtils.remove(entry, 5);
                        entry = (String[]) ArrayUtils.remove(entry, 5);
                        entry = (String[]) ArrayUtils.remove(entry, 5);
                        entry = (String[]) ArrayUtils.remove(entry, 5);

                        entry = (String[]) ArrayUtils.remove(entry, 7);
                        entry = (String[]) ArrayUtils.remove(entry, 7);
                        entry = (String[]) ArrayUtils.remove(entry, 7);
                        entry = (String[]) ArrayUtils.remove(entry, 7);
                        entry = (String[]) ArrayUtils.remove(entry, 7);
                        entry = (String[]) ArrayUtils.remove(entry, 7);

                        entry = (String[]) ArrayUtils.remove(entry, 10);
                        entry = (String[]) ArrayUtils.remove(entry, 10);
                        entry = (String[]) ArrayUtils.remove(entry, 10);

                        System.out.println(ReflectionToStringBuilder.toString(entry));
                        writer.writeNext(entry);
                    }
                    writer.close();

                }
            }

            try {
                Desktop desktop = Desktop.getDesktop();
                desktop.open(theDir);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        } catch (IOException ex) {
            Logger.getLogger(ReporteDeHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDeHorarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDeHorarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLoginSIIAU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldNIP;
    private javax.swing.JTextField jTextFieldCodigo;
    // End of variables declaration//GEN-END:variables
}
